#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_Lotus")]
	public partial class Base_De_DatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_Estudiante(Tbl_Estudiante instance);
    partial void UpdateTbl_Estudiante(Tbl_Estudiante instance);
    partial void DeleteTbl_Estudiante(Tbl_Estudiante instance);
    partial void InsertTbl_Evaluacion(Tbl_Evaluacion instance);
    partial void UpdateTbl_Evaluacion(Tbl_Evaluacion instance);
    partial void DeleteTbl_Evaluacion(Tbl_Evaluacion instance);
    partial void InsertTbl_Grado(Tbl_Grado instance);
    partial void UpdateTbl_Grado(Tbl_Grado instance);
    partial void DeleteTbl_Grado(Tbl_Grado instance);
    partial void InsertTbl_Habilidades(Tbl_Habilidades instance);
    partial void UpdateTbl_Habilidades(Tbl_Habilidades instance);
    partial void DeleteTbl_Habilidades(Tbl_Habilidades instance);
    partial void InsertTbl_Intentos(Tbl_Intentos instance);
    partial void UpdateTbl_Intentos(Tbl_Intentos instance);
    partial void DeleteTbl_Intentos(Tbl_Intentos instance);
    partial void InsertTbl_Maestro(Tbl_Maestro instance);
    partial void UpdateTbl_Maestro(Tbl_Maestro instance);
    partial void DeleteTbl_Maestro(Tbl_Maestro instance);
    partial void InsertTbl_Materia(Tbl_Materia instance);
    partial void UpdateTbl_Materia(Tbl_Materia instance);
    partial void DeleteTbl_Materia(Tbl_Materia instance);
    partial void InsertTbl_Padre_Famila(Tbl_Padre_Famila instance);
    partial void UpdateTbl_Padre_Famila(Tbl_Padre_Famila instance);
    partial void DeleteTbl_Padre_Famila(Tbl_Padre_Famila instance);
    partial void InsertTbl_Respuestas(Tbl_Respuestas instance);
    partial void UpdateTbl_Respuestas(Tbl_Respuestas instance);
    partial void DeleteTbl_Respuestas(Tbl_Respuestas instance);
    partial void InsertTbl_Seccion(Tbl_Seccion instance);
    partial void UpdateTbl_Seccion(Tbl_Seccion instance);
    partial void DeleteTbl_Seccion(Tbl_Seccion instance);
    #endregion
		
		public Base_De_DatosDataContext() : 
				base(global::Modelo.Properties.Settings.Default.db_LotusConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Base_De_DatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Base_De_DatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Base_De_DatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Base_De_DatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tiene_materias> Tiene_materias
		{
			get
			{
				return this.GetTable<Tiene_materias>();
			}
		}
		
		public System.Data.Linq.Table<Clasifica_Habilidad> Clasifica_Habilidad
		{
			get
			{
				return this.GetTable<Clasifica_Habilidad>();
			}
		}
		
		public System.Data.Linq.Table<MaestroYestudiante> MaestroYestudiante
		{
			get
			{
				return this.GetTable<MaestroYestudiante>();
			}
		}
		
		public System.Data.Linq.Table<RealizaEvaluacion> RealizaEvaluacion
		{
			get
			{
				return this.GetTable<RealizaEvaluacion>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Calificaciones> Tbl_Calificaciones
		{
			get
			{
				return this.GetTable<Tbl_Calificaciones>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Estudiante> Tbl_Estudiante
		{
			get
			{
				return this.GetTable<Tbl_Estudiante>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Evaluacion> Tbl_Evaluacion
		{
			get
			{
				return this.GetTable<Tbl_Evaluacion>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Grado> Tbl_Grado
		{
			get
			{
				return this.GetTable<Tbl_Grado>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Habilidades> Tbl_Habilidades
		{
			get
			{
				return this.GetTable<Tbl_Habilidades>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Intentos> Tbl_Intentos
		{
			get
			{
				return this.GetTable<Tbl_Intentos>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Maestro> Tbl_Maestro
		{
			get
			{
				return this.GetTable<Tbl_Maestro>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Materia> Tbl_Materia
		{
			get
			{
				return this.GetTable<Tbl_Materia>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Padre_Famila> Tbl_Padre_Famila
		{
			get
			{
				return this.GetTable<Tbl_Padre_Famila>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Respuestas> Tbl_Respuestas
		{
			get
			{
				return this.GetTable<Tbl_Respuestas>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Seccion> Tbl_Seccion
		{
			get
			{
				return this.GetTable<Tbl_Seccion>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InicioSesionDocente")]
		public ISingleResult<InicioSesionDocenteResult> InicioSesionDocente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioDocente", DbType="VarChar(50)")] string usuarioDocente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(50)")] string contraseña)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioDocente, contraseña);
			return ((ISingleResult<InicioSesionDocenteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IniciaSesionPadre")]
		public ISingleResult<IniciaSesionPadreResult> IniciaSesionPadre([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioPadre", DbType="VarChar(50)")] string usuarioPadre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(50)")] string contraseña)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioPadre, contraseña);
			return ((ISingleResult<IniciaSesionPadreResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tiene_materias")]
	public partial class Tiene_materias
	{
		
		private int _ID_Estudiante;
		
		private int _Nombre_Materia;
		
		public Tiene_materias()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Estudiante", DbType="Int NOT NULL")]
		public int ID_Estudiante
		{
			get
			{
				return this._ID_Estudiante;
			}
			set
			{
				if ((this._ID_Estudiante != value))
				{
					this._ID_Estudiante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Materia", DbType="Int NOT NULL")]
		public int Nombre_Materia
		{
			get
			{
				return this._Nombre_Materia;
			}
			set
			{
				if ((this._Nombre_Materia != value))
				{
					this._Nombre_Materia = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clasifica_Habilidad")]
	public partial class Clasifica_Habilidad
	{
		
		private int _ID_habilidad;
		
		private int _ID_Estudiante;
		
		public Clasifica_Habilidad()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_habilidad", DbType="Int NOT NULL")]
		public int ID_habilidad
		{
			get
			{
				return this._ID_habilidad;
			}
			set
			{
				if ((this._ID_habilidad != value))
				{
					this._ID_habilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Estudiante", DbType="Int NOT NULL")]
		public int ID_Estudiante
		{
			get
			{
				return this._ID_Estudiante;
			}
			set
			{
				if ((this._ID_Estudiante != value))
				{
					this._ID_Estudiante = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MaestroYestudiante")]
	public partial class MaestroYestudiante
	{
		
		private int _ID_Estudiante;
		
		private int _ID_Maestro;
		
		public MaestroYestudiante()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Estudiante", DbType="Int NOT NULL")]
		public int ID_Estudiante
		{
			get
			{
				return this._ID_Estudiante;
			}
			set
			{
				if ((this._ID_Estudiante != value))
				{
					this._ID_Estudiante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Maestro", DbType="Int NOT NULL")]
		public int ID_Maestro
		{
			get
			{
				return this._ID_Maestro;
			}
			set
			{
				if ((this._ID_Maestro != value))
				{
					this._ID_Maestro = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RealizaEvaluacion")]
	public partial class RealizaEvaluacion
	{
		
		private int _ID_Estudiante;
		
		private int _ID_Evalucion;
		
		public RealizaEvaluacion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Estudiante", DbType="Int NOT NULL")]
		public int ID_Estudiante
		{
			get
			{
				return this._ID_Estudiante;
			}
			set
			{
				if ((this._ID_Estudiante != value))
				{
					this._ID_Estudiante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Evalucion", DbType="Int NOT NULL")]
		public int ID_Evalucion
		{
			get
			{
				return this._ID_Evalucion;
			}
			set
			{
				if ((this._ID_Evalucion != value))
				{
					this._ID_Evalucion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Calificaciones")]
	public partial class Tbl_Calificaciones
	{
		
		private int _Cantidad;
		
		private int _Nombre_Materia;
		
		private int _ID_Estudiante;
		
		public Tbl_Calificaciones()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Materia", DbType="Int NOT NULL")]
		public int Nombre_Materia
		{
			get
			{
				return this._Nombre_Materia;
			}
			set
			{
				if ((this._Nombre_Materia != value))
				{
					this._Nombre_Materia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Estudiante", DbType="Int NOT NULL")]
		public int ID_Estudiante
		{
			get
			{
				return this._ID_Estudiante;
			}
			set
			{
				if ((this._ID_Estudiante != value))
				{
					this._ID_Estudiante = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Estudiante")]
	public partial class Tbl_Estudiante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Estudiante;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private int _Numero_seccion;
		
		private int _ID_Padre;
		
		private int _Edad;
		
		private string _Sexo;
		
		private string _Discapacidades;
		
		private string _habitantesHogar;
		
		private string _Departamento;
		
		private string _Municipio;
		
		private string _Barrio;
		
		private bool _PoseeEquipo;
		
		private bool _PoseeTelefono;
		
		private bool _Intermet;
		
		private EntityRef<Tbl_Padre_Famila> _Tbl_Padre_Famila;
		
		private EntityRef<Tbl_Seccion> _Tbl_Seccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EstudianteChanging(int value);
    partial void OnID_EstudianteChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnNumero_seccionChanging(int value);
    partial void OnNumero_seccionChanged();
    partial void OnID_PadreChanging(int value);
    partial void OnID_PadreChanged();
    partial void OnEdadChanging(int value);
    partial void OnEdadChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnDiscapacidadesChanging(string value);
    partial void OnDiscapacidadesChanged();
    partial void OnhabitantesHogarChanging(string value);
    partial void OnhabitantesHogarChanged();
    partial void OnDepartamentoChanging(string value);
    partial void OnDepartamentoChanged();
    partial void OnMunicipioChanging(string value);
    partial void OnMunicipioChanged();
    partial void OnBarrioChanging(string value);
    partial void OnBarrioChanged();
    partial void OnPoseeEquipoChanging(bool value);
    partial void OnPoseeEquipoChanged();
    partial void OnPoseeTelefonoChanging(bool value);
    partial void OnPoseeTelefonoChanged();
    partial void OnIntermetChanging(bool value);
    partial void OnIntermetChanged();
    #endregion
		
		public Tbl_Estudiante()
		{
			this._Tbl_Padre_Famila = default(EntityRef<Tbl_Padre_Famila>);
			this._Tbl_Seccion = default(EntityRef<Tbl_Seccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Estudiante", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Estudiante
		{
			get
			{
				return this._ID_Estudiante;
			}
			set
			{
				if ((this._ID_Estudiante != value))
				{
					this.OnID_EstudianteChanging(value);
					this.SendPropertyChanging();
					this._ID_Estudiante = value;
					this.SendPropertyChanged("ID_Estudiante");
					this.OnID_EstudianteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_seccion", DbType="Int NOT NULL")]
		public int Numero_seccion
		{
			get
			{
				return this._Numero_seccion;
			}
			set
			{
				if ((this._Numero_seccion != value))
				{
					if (this._Tbl_Seccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNumero_seccionChanging(value);
					this.SendPropertyChanging();
					this._Numero_seccion = value;
					this.SendPropertyChanged("Numero_seccion");
					this.OnNumero_seccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Padre", DbType="Int NOT NULL")]
		public int ID_Padre
		{
			get
			{
				return this._ID_Padre;
			}
			set
			{
				if ((this._ID_Padre != value))
				{
					if (this._Tbl_Padre_Famila.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PadreChanging(value);
					this.SendPropertyChanging();
					this._ID_Padre = value;
					this.SendPropertyChanged("ID_Padre");
					this.OnID_PadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int NOT NULL")]
		public int Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this.OnEdadChanging(value);
					this.SendPropertyChanging();
					this._Edad = value;
					this.SendPropertyChanged("Edad");
					this.OnEdadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discapacidades", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Discapacidades
		{
			get
			{
				return this._Discapacidades;
			}
			set
			{
				if ((this._Discapacidades != value))
				{
					this.OnDiscapacidadesChanging(value);
					this.SendPropertyChanging();
					this._Discapacidades = value;
					this.SendPropertyChanged("Discapacidades");
					this.OnDiscapacidadesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_habitantesHogar", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string habitantesHogar
		{
			get
			{
				return this._habitantesHogar;
			}
			set
			{
				if ((this._habitantesHogar != value))
				{
					this.OnhabitantesHogarChanging(value);
					this.SendPropertyChanging();
					this._habitantesHogar = value;
					this.SendPropertyChanged("habitantesHogar");
					this.OnhabitantesHogarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this.OnDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._Departamento = value;
					this.SendPropertyChanged("Departamento");
					this.OnDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this.OnMunicipioChanging(value);
					this.SendPropertyChanging();
					this._Municipio = value;
					this.SendPropertyChanged("Municipio");
					this.OnMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barrio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Barrio
		{
			get
			{
				return this._Barrio;
			}
			set
			{
				if ((this._Barrio != value))
				{
					this.OnBarrioChanging(value);
					this.SendPropertyChanging();
					this._Barrio = value;
					this.SendPropertyChanged("Barrio");
					this.OnBarrioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoseeEquipo", DbType="Bit NOT NULL")]
		public bool PoseeEquipo
		{
			get
			{
				return this._PoseeEquipo;
			}
			set
			{
				if ((this._PoseeEquipo != value))
				{
					this.OnPoseeEquipoChanging(value);
					this.SendPropertyChanging();
					this._PoseeEquipo = value;
					this.SendPropertyChanged("PoseeEquipo");
					this.OnPoseeEquipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoseeTelefono", DbType="Bit NOT NULL")]
		public bool PoseeTelefono
		{
			get
			{
				return this._PoseeTelefono;
			}
			set
			{
				if ((this._PoseeTelefono != value))
				{
					this.OnPoseeTelefonoChanging(value);
					this.SendPropertyChanging();
					this._PoseeTelefono = value;
					this.SendPropertyChanged("PoseeTelefono");
					this.OnPoseeTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intermet", DbType="Bit NOT NULL")]
		public bool Intermet
		{
			get
			{
				return this._Intermet;
			}
			set
			{
				if ((this._Intermet != value))
				{
					this.OnIntermetChanging(value);
					this.SendPropertyChanging();
					this._Intermet = value;
					this.SendPropertyChanged("Intermet");
					this.OnIntermetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Padre_Famila_Tbl_Estudiante", Storage="_Tbl_Padre_Famila", ThisKey="ID_Padre", OtherKey="ID_Padre", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Tbl_Padre_Famila Tbl_Padre_Famila
		{
			get
			{
				return this._Tbl_Padre_Famila.Entity;
			}
			set
			{
				Tbl_Padre_Famila previousValue = this._Tbl_Padre_Famila.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Padre_Famila.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Padre_Famila.Entity = null;
						previousValue.Tbl_Estudiante.Remove(this);
					}
					this._Tbl_Padre_Famila.Entity = value;
					if ((value != null))
					{
						value.Tbl_Estudiante.Add(this);
						this._ID_Padre = value.ID_Padre;
					}
					else
					{
						this._ID_Padre = default(int);
					}
					this.SendPropertyChanged("Tbl_Padre_Famila");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Seccion_Tbl_Estudiante", Storage="_Tbl_Seccion", ThisKey="Numero_seccion", OtherKey="Numero_seccion", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Tbl_Seccion Tbl_Seccion
		{
			get
			{
				return this._Tbl_Seccion.Entity;
			}
			set
			{
				Tbl_Seccion previousValue = this._Tbl_Seccion.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Seccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Seccion.Entity = null;
						previousValue.Tbl_Estudiante.Remove(this);
					}
					this._Tbl_Seccion.Entity = value;
					if ((value != null))
					{
						value.Tbl_Estudiante.Add(this);
						this._Numero_seccion = value.Numero_seccion;
					}
					else
					{
						this._Numero_seccion = default(int);
					}
					this.SendPropertyChanged("Tbl_Seccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Evaluacion")]
	public partial class Tbl_Evaluacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Evalucion;
		
		private string _EjercisioAsignado;
		
		private string _RespuestaCorrecta;
		
		private int _CantidadDeIntentos;
		
		private int _RespuestasCorrectas;
		
		private EntityRef<Tbl_Intentos> _Tbl_Intentos;
		
		private EntityRef<Tbl_Respuestas> _Tbl_Respuestas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EvalucionChanging(int value);
    partial void OnID_EvalucionChanged();
    partial void OnEjercisioAsignadoChanging(string value);
    partial void OnEjercisioAsignadoChanged();
    partial void OnRespuestaCorrectaChanging(string value);
    partial void OnRespuestaCorrectaChanged();
    partial void OnCantidadDeIntentosChanging(int value);
    partial void OnCantidadDeIntentosChanged();
    partial void OnRespuestasCorrectasChanging(int value);
    partial void OnRespuestasCorrectasChanged();
    #endregion
		
		public Tbl_Evaluacion()
		{
			this._Tbl_Intentos = default(EntityRef<Tbl_Intentos>);
			this._Tbl_Respuestas = default(EntityRef<Tbl_Respuestas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Evalucion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Evalucion
		{
			get
			{
				return this._ID_Evalucion;
			}
			set
			{
				if ((this._ID_Evalucion != value))
				{
					this.OnID_EvalucionChanging(value);
					this.SendPropertyChanging();
					this._ID_Evalucion = value;
					this.SendPropertyChanged("ID_Evalucion");
					this.OnID_EvalucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EjercisioAsignado", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EjercisioAsignado
		{
			get
			{
				return this._EjercisioAsignado;
			}
			set
			{
				if ((this._EjercisioAsignado != value))
				{
					this.OnEjercisioAsignadoChanging(value);
					this.SendPropertyChanging();
					this._EjercisioAsignado = value;
					this.SendPropertyChanged("EjercisioAsignado");
					this.OnEjercisioAsignadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RespuestaCorrecta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RespuestaCorrecta
		{
			get
			{
				return this._RespuestaCorrecta;
			}
			set
			{
				if ((this._RespuestaCorrecta != value))
				{
					this.OnRespuestaCorrectaChanging(value);
					this.SendPropertyChanging();
					this._RespuestaCorrecta = value;
					this.SendPropertyChanged("RespuestaCorrecta");
					this.OnRespuestaCorrectaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadDeIntentos", DbType="Int NOT NULL")]
		public int CantidadDeIntentos
		{
			get
			{
				return this._CantidadDeIntentos;
			}
			set
			{
				if ((this._CantidadDeIntentos != value))
				{
					if (this._Tbl_Intentos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCantidadDeIntentosChanging(value);
					this.SendPropertyChanging();
					this._CantidadDeIntentos = value;
					this.SendPropertyChanged("CantidadDeIntentos");
					this.OnCantidadDeIntentosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RespuestasCorrectas", DbType="Int NOT NULL")]
		public int RespuestasCorrectas
		{
			get
			{
				return this._RespuestasCorrectas;
			}
			set
			{
				if ((this._RespuestasCorrectas != value))
				{
					if (this._Tbl_Respuestas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRespuestasCorrectasChanging(value);
					this.SendPropertyChanging();
					this._RespuestasCorrectas = value;
					this.SendPropertyChanged("RespuestasCorrectas");
					this.OnRespuestasCorrectasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Intentos_Tbl_Evaluacion", Storage="_Tbl_Intentos", ThisKey="CantidadDeIntentos", OtherKey="CantidadDeIntentos", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Tbl_Intentos Tbl_Intentos
		{
			get
			{
				return this._Tbl_Intentos.Entity;
			}
			set
			{
				Tbl_Intentos previousValue = this._Tbl_Intentos.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Intentos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Intentos.Entity = null;
						previousValue.Tbl_Evaluacion.Remove(this);
					}
					this._Tbl_Intentos.Entity = value;
					if ((value != null))
					{
						value.Tbl_Evaluacion.Add(this);
						this._CantidadDeIntentos = value.CantidadDeIntentos;
					}
					else
					{
						this._CantidadDeIntentos = default(int);
					}
					this.SendPropertyChanged("Tbl_Intentos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Respuestas_Tbl_Evaluacion", Storage="_Tbl_Respuestas", ThisKey="RespuestasCorrectas", OtherKey="RespuestasCorrectas", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Tbl_Respuestas Tbl_Respuestas
		{
			get
			{
				return this._Tbl_Respuestas.Entity;
			}
			set
			{
				Tbl_Respuestas previousValue = this._Tbl_Respuestas.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Respuestas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Respuestas.Entity = null;
						previousValue.Tbl_Evaluacion.Remove(this);
					}
					this._Tbl_Respuestas.Entity = value;
					if ((value != null))
					{
						value.Tbl_Evaluacion.Add(this);
						this._RespuestasCorrectas = value.RespuestasCorrectas;
					}
					else
					{
						this._RespuestasCorrectas = default(int);
					}
					this.SendPropertyChanged("Tbl_Respuestas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Grado")]
	public partial class Tbl_Grado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Numero_Grado;
		
		private EntitySet<Tbl_Seccion> _Tbl_Seccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumero_GradoChanging(int value);
    partial void OnNumero_GradoChanged();
    #endregion
		
		public Tbl_Grado()
		{
			this._Tbl_Seccion = new EntitySet<Tbl_Seccion>(new Action<Tbl_Seccion>(this.attach_Tbl_Seccion), new Action<Tbl_Seccion>(this.detach_Tbl_Seccion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Grado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Numero_Grado
		{
			get
			{
				return this._Numero_Grado;
			}
			set
			{
				if ((this._Numero_Grado != value))
				{
					this.OnNumero_GradoChanging(value);
					this.SendPropertyChanging();
					this._Numero_Grado = value;
					this.SendPropertyChanged("Numero_Grado");
					this.OnNumero_GradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Grado_Tbl_Seccion", Storage="_Tbl_Seccion", ThisKey="Numero_Grado", OtherKey="Numero_Grado")]
		public EntitySet<Tbl_Seccion> Tbl_Seccion
		{
			get
			{
				return this._Tbl_Seccion;
			}
			set
			{
				this._Tbl_Seccion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Seccion(Tbl_Seccion entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Grado = this;
		}
		
		private void detach_Tbl_Seccion(Tbl_Seccion entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Grado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Habilidades")]
	public partial class Tbl_Habilidades : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_habilidad;
		
		private string _Nombre_Habilidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_habilidadChanging(int value);
    partial void OnID_habilidadChanged();
    partial void OnNombre_HabilidadChanging(string value);
    partial void OnNombre_HabilidadChanged();
    #endregion
		
		public Tbl_Habilidades()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_habilidad", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_habilidad
		{
			get
			{
				return this._ID_habilidad;
			}
			set
			{
				if ((this._ID_habilidad != value))
				{
					this.OnID_habilidadChanging(value);
					this.SendPropertyChanging();
					this._ID_habilidad = value;
					this.SendPropertyChanged("ID_habilidad");
					this.OnID_habilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Habilidad", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Nombre_Habilidad
		{
			get
			{
				return this._Nombre_Habilidad;
			}
			set
			{
				if ((this._Nombre_Habilidad != value))
				{
					this.OnNombre_HabilidadChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Habilidad = value;
					this.SendPropertyChanged("Nombre_Habilidad");
					this.OnNombre_HabilidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Intentos")]
	public partial class Tbl_Intentos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CantidadDeIntentos;
		
		private EntitySet<Tbl_Evaluacion> _Tbl_Evaluacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCantidadDeIntentosChanging(int value);
    partial void OnCantidadDeIntentosChanged();
    #endregion
		
		public Tbl_Intentos()
		{
			this._Tbl_Evaluacion = new EntitySet<Tbl_Evaluacion>(new Action<Tbl_Evaluacion>(this.attach_Tbl_Evaluacion), new Action<Tbl_Evaluacion>(this.detach_Tbl_Evaluacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadDeIntentos", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CantidadDeIntentos
		{
			get
			{
				return this._CantidadDeIntentos;
			}
			set
			{
				if ((this._CantidadDeIntentos != value))
				{
					this.OnCantidadDeIntentosChanging(value);
					this.SendPropertyChanging();
					this._CantidadDeIntentos = value;
					this.SendPropertyChanged("CantidadDeIntentos");
					this.OnCantidadDeIntentosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Intentos_Tbl_Evaluacion", Storage="_Tbl_Evaluacion", ThisKey="CantidadDeIntentos", OtherKey="CantidadDeIntentos")]
		public EntitySet<Tbl_Evaluacion> Tbl_Evaluacion
		{
			get
			{
				return this._Tbl_Evaluacion;
			}
			set
			{
				this._Tbl_Evaluacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Evaluacion(Tbl_Evaluacion entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Intentos = this;
		}
		
		private void detach_Tbl_Evaluacion(Tbl_Evaluacion entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Intentos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Maestro")]
	public partial class Tbl_Maestro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Maestro;
		
		private string _Correo;
		
		private string _contraseña;
		
		private string _PresguntaSeguridad;
		
		private string _RespuestasPreguntaSeguridad;
		
		private bool _linea;
		
		private string _NombreDocente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MaestroChanging(int value);
    partial void OnID_MaestroChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void OnPresguntaSeguridadChanging(string value);
    partial void OnPresguntaSeguridadChanged();
    partial void OnRespuestasPreguntaSeguridadChanging(string value);
    partial void OnRespuestasPreguntaSeguridadChanged();
    partial void OnlineaChanging(bool value);
    partial void OnlineaChanged();
    partial void OnNombreDocenteChanging(string value);
    partial void OnNombreDocenteChanged();
    #endregion
		
		public Tbl_Maestro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Maestro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Maestro
		{
			get
			{
				return this._ID_Maestro;
			}
			set
			{
				if ((this._ID_Maestro != value))
				{
					this.OnID_MaestroChanging(value);
					this.SendPropertyChanging();
					this._ID_Maestro = value;
					this.SendPropertyChanged("ID_Maestro");
					this.OnID_MaestroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresguntaSeguridad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PresguntaSeguridad
		{
			get
			{
				return this._PresguntaSeguridad;
			}
			set
			{
				if ((this._PresguntaSeguridad != value))
				{
					this.OnPresguntaSeguridadChanging(value);
					this.SendPropertyChanging();
					this._PresguntaSeguridad = value;
					this.SendPropertyChanged("PresguntaSeguridad");
					this.OnPresguntaSeguridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RespuestasPreguntaSeguridad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RespuestasPreguntaSeguridad
		{
			get
			{
				return this._RespuestasPreguntaSeguridad;
			}
			set
			{
				if ((this._RespuestasPreguntaSeguridad != value))
				{
					this.OnRespuestasPreguntaSeguridadChanging(value);
					this.SendPropertyChanging();
					this._RespuestasPreguntaSeguridad = value;
					this.SendPropertyChanged("RespuestasPreguntaSeguridad");
					this.OnRespuestasPreguntaSeguridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linea", DbType="Bit NOT NULL")]
		public bool linea
		{
			get
			{
				return this._linea;
			}
			set
			{
				if ((this._linea != value))
				{
					this.OnlineaChanging(value);
					this.SendPropertyChanging();
					this._linea = value;
					this.SendPropertyChanged("linea");
					this.OnlineaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreDocente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreDocente
		{
			get
			{
				return this._NombreDocente;
			}
			set
			{
				if ((this._NombreDocente != value))
				{
					this.OnNombreDocenteChanging(value);
					this.SendPropertyChanging();
					this._NombreDocente = value;
					this.SendPropertyChanged("NombreDocente");
					this.OnNombreDocenteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Materia")]
	public partial class Tbl_Materia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Nombre_Materia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNombre_MateriaChanging(int value);
    partial void OnNombre_MateriaChanged();
    #endregion
		
		public Tbl_Materia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Materia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Nombre_Materia
		{
			get
			{
				return this._Nombre_Materia;
			}
			set
			{
				if ((this._Nombre_Materia != value))
				{
					this.OnNombre_MateriaChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Materia = value;
					this.SendPropertyChanged("Nombre_Materia");
					this.OnNombre_MateriaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Padre_Famila")]
	public partial class Tbl_Padre_Famila : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Padre;
		
		private string _Nombre;
		
		private string _apellido;
		
		private string _correo;
		
		private string _contraseña;
		
		private string _PreguntaSeguridad;
		
		private string _RespuestaPreguntaSeguridad;
		
		private bool _linea;
		
		private EntitySet<Tbl_Estudiante> _Tbl_Estudiante;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PadreChanging(int value);
    partial void OnID_PadreChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void OnPreguntaSeguridadChanging(string value);
    partial void OnPreguntaSeguridadChanged();
    partial void OnRespuestaPreguntaSeguridadChanging(string value);
    partial void OnRespuestaPreguntaSeguridadChanged();
    partial void OnlineaChanging(bool value);
    partial void OnlineaChanged();
    #endregion
		
		public Tbl_Padre_Famila()
		{
			this._Tbl_Estudiante = new EntitySet<Tbl_Estudiante>(new Action<Tbl_Estudiante>(this.attach_Tbl_Estudiante), new Action<Tbl_Estudiante>(this.detach_Tbl_Estudiante));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Padre", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Padre
		{
			get
			{
				return this._ID_Padre;
			}
			set
			{
				if ((this._ID_Padre != value))
				{
					this.OnID_PadreChanging(value);
					this.SendPropertyChanging();
					this._ID_Padre = value;
					this.SendPropertyChanged("ID_Padre");
					this.OnID_PadreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(90) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreguntaSeguridad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PreguntaSeguridad
		{
			get
			{
				return this._PreguntaSeguridad;
			}
			set
			{
				if ((this._PreguntaSeguridad != value))
				{
					this.OnPreguntaSeguridadChanging(value);
					this.SendPropertyChanging();
					this._PreguntaSeguridad = value;
					this.SendPropertyChanged("PreguntaSeguridad");
					this.OnPreguntaSeguridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RespuestaPreguntaSeguridad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RespuestaPreguntaSeguridad
		{
			get
			{
				return this._RespuestaPreguntaSeguridad;
			}
			set
			{
				if ((this._RespuestaPreguntaSeguridad != value))
				{
					this.OnRespuestaPreguntaSeguridadChanging(value);
					this.SendPropertyChanging();
					this._RespuestaPreguntaSeguridad = value;
					this.SendPropertyChanged("RespuestaPreguntaSeguridad");
					this.OnRespuestaPreguntaSeguridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linea", DbType="Bit NOT NULL")]
		public bool linea
		{
			get
			{
				return this._linea;
			}
			set
			{
				if ((this._linea != value))
				{
					this.OnlineaChanging(value);
					this.SendPropertyChanging();
					this._linea = value;
					this.SendPropertyChanged("linea");
					this.OnlineaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Padre_Famila_Tbl_Estudiante", Storage="_Tbl_Estudiante", ThisKey="ID_Padre", OtherKey="ID_Padre")]
		public EntitySet<Tbl_Estudiante> Tbl_Estudiante
		{
			get
			{
				return this._Tbl_Estudiante;
			}
			set
			{
				this._Tbl_Estudiante.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Estudiante(Tbl_Estudiante entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Padre_Famila = this;
		}
		
		private void detach_Tbl_Estudiante(Tbl_Estudiante entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Padre_Famila = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Respuestas")]
	public partial class Tbl_Respuestas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RespuestasCorrectas;
		
		private EntitySet<Tbl_Evaluacion> _Tbl_Evaluacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRespuestasCorrectasChanging(int value);
    partial void OnRespuestasCorrectasChanged();
    #endregion
		
		public Tbl_Respuestas()
		{
			this._Tbl_Evaluacion = new EntitySet<Tbl_Evaluacion>(new Action<Tbl_Evaluacion>(this.attach_Tbl_Evaluacion), new Action<Tbl_Evaluacion>(this.detach_Tbl_Evaluacion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RespuestasCorrectas", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RespuestasCorrectas
		{
			get
			{
				return this._RespuestasCorrectas;
			}
			set
			{
				if ((this._RespuestasCorrectas != value))
				{
					this.OnRespuestasCorrectasChanging(value);
					this.SendPropertyChanging();
					this._RespuestasCorrectas = value;
					this.SendPropertyChanged("RespuestasCorrectas");
					this.OnRespuestasCorrectasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Respuestas_Tbl_Evaluacion", Storage="_Tbl_Evaluacion", ThisKey="RespuestasCorrectas", OtherKey="RespuestasCorrectas")]
		public EntitySet<Tbl_Evaluacion> Tbl_Evaluacion
		{
			get
			{
				return this._Tbl_Evaluacion;
			}
			set
			{
				this._Tbl_Evaluacion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Evaluacion(Tbl_Evaluacion entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Respuestas = this;
		}
		
		private void detach_Tbl_Evaluacion(Tbl_Evaluacion entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Respuestas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Seccion")]
	public partial class Tbl_Seccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Numero_seccion;
		
		private int _Numero_Grado;
		
		private EntitySet<Tbl_Estudiante> _Tbl_Estudiante;
		
		private EntityRef<Tbl_Grado> _Tbl_Grado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumero_seccionChanging(int value);
    partial void OnNumero_seccionChanged();
    partial void OnNumero_GradoChanging(int value);
    partial void OnNumero_GradoChanged();
    #endregion
		
		public Tbl_Seccion()
		{
			this._Tbl_Estudiante = new EntitySet<Tbl_Estudiante>(new Action<Tbl_Estudiante>(this.attach_Tbl_Estudiante), new Action<Tbl_Estudiante>(this.detach_Tbl_Estudiante));
			this._Tbl_Grado = default(EntityRef<Tbl_Grado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_seccion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Numero_seccion
		{
			get
			{
				return this._Numero_seccion;
			}
			set
			{
				if ((this._Numero_seccion != value))
				{
					this.OnNumero_seccionChanging(value);
					this.SendPropertyChanging();
					this._Numero_seccion = value;
					this.SendPropertyChanged("Numero_seccion");
					this.OnNumero_seccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Grado", DbType="Int NOT NULL")]
		public int Numero_Grado
		{
			get
			{
				return this._Numero_Grado;
			}
			set
			{
				if ((this._Numero_Grado != value))
				{
					if (this._Tbl_Grado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNumero_GradoChanging(value);
					this.SendPropertyChanging();
					this._Numero_Grado = value;
					this.SendPropertyChanged("Numero_Grado");
					this.OnNumero_GradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Seccion_Tbl_Estudiante", Storage="_Tbl_Estudiante", ThisKey="Numero_seccion", OtherKey="Numero_seccion")]
		public EntitySet<Tbl_Estudiante> Tbl_Estudiante
		{
			get
			{
				return this._Tbl_Estudiante;
			}
			set
			{
				this._Tbl_Estudiante.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Grado_Tbl_Seccion", Storage="_Tbl_Grado", ThisKey="Numero_Grado", OtherKey="Numero_Grado", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Tbl_Grado Tbl_Grado
		{
			get
			{
				return this._Tbl_Grado.Entity;
			}
			set
			{
				Tbl_Grado previousValue = this._Tbl_Grado.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Grado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Grado.Entity = null;
						previousValue.Tbl_Seccion.Remove(this);
					}
					this._Tbl_Grado.Entity = value;
					if ((value != null))
					{
						value.Tbl_Seccion.Add(this);
						this._Numero_Grado = value.Numero_Grado;
					}
					else
					{
						this._Numero_Grado = default(int);
					}
					this.SendPropertyChanged("Tbl_Grado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Estudiante(Tbl_Estudiante entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Seccion = this;
		}
		
		private void detach_Tbl_Estudiante(Tbl_Estudiante entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Seccion = null;
		}
	}
	
	public partial class InicioSesionDocenteResult
	{
		
		private System.Nullable<bool> _Resultado;
		
		public InicioSesionDocenteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resultado", DbType="Bit")]
		public System.Nullable<bool> Resultado
		{
			get
			{
				return this._Resultado;
			}
			set
			{
				if ((this._Resultado != value))
				{
					this._Resultado = value;
				}
			}
		}
	}
	
	public partial class IniciaSesionPadreResult
	{
		
		private System.Nullable<bool> _ResultadoP;
		
		public IniciaSesionPadreResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultadoP", DbType="Bit")]
		public System.Nullable<bool> ResultadoP
		{
			get
			{
				return this._ResultadoP;
			}
			set
			{
				if ((this._ResultadoP != value))
				{
					this._ResultadoP = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
